# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/Quasar/Downloads/SEAL-master/basic encrypted controller"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/Quasar/Downloads/SEAL-master/basic encrypted controller"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/Quasar/Downloads/SEAL-master/basic encrypted controller/CMakeFiles" "/Users/Quasar/Downloads/SEAL-master/basic encrypted controller/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/Quasar/Downloads/SEAL-master/basic encrypted controller/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named encrypted_controller

# Build rule for target.
encrypted_controller: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 encrypted_controller
.PHONY : encrypted_controller

# fast build rule for target.
encrypted_controller/fast:
	$(MAKE) -f CMakeFiles/encrypted_controller.dir/build.make CMakeFiles/encrypted_controller.dir/build
.PHONY : encrypted_controller/fast

encrypted_controller_main.o: encrypted_controller_main.cpp.o

.PHONY : encrypted_controller_main.o

# target to build an object file
encrypted_controller_main.cpp.o:
	$(MAKE) -f CMakeFiles/encrypted_controller.dir/build.make CMakeFiles/encrypted_controller.dir/encrypted_controller_main.cpp.o
.PHONY : encrypted_controller_main.cpp.o

encrypted_controller_main.i: encrypted_controller_main.cpp.i

.PHONY : encrypted_controller_main.i

# target to preprocess a source file
encrypted_controller_main.cpp.i:
	$(MAKE) -f CMakeFiles/encrypted_controller.dir/build.make CMakeFiles/encrypted_controller.dir/encrypted_controller_main.cpp.i
.PHONY : encrypted_controller_main.cpp.i

encrypted_controller_main.s: encrypted_controller_main.cpp.s

.PHONY : encrypted_controller_main.s

# target to generate assembly for a file
encrypted_controller_main.cpp.s:
	$(MAKE) -f CMakeFiles/encrypted_controller.dir/build.make CMakeFiles/encrypted_controller.dir/encrypted_controller_main.cpp.s
.PHONY : encrypted_controller_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... encrypted_controller"
	@echo "... encrypted_controller_main.o"
	@echo "... encrypted_controller_main.i"
	@echo "... encrypted_controller_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

